### ISSUE TITLE
Настройки силы, маны, хп у монстров

### ISSUE THREAD

**Issue by zTerragor** [WarheadCore/WarheadBand#147]
### Current Behaviour

Не регулируются настройки в конфиге 
Rate.Creature.Normal.SpellDamage          = 1
Rate.Creature.Elite.Elite.SpellDamage     = 1
Rate.Creature.Elite.RARE.SpellDamage      = 1
Rate.Creature.Elite.RAREELITE.SpellDamage = 1
Rate.Creature.Elite.WORLDBOSS.SpellDamage = 1
Другие значения не дает выставить

### Expected Blizzlike Behaviour

Не регулируются настройки в конфиге 
Rate.Creature.Normal.SpellDamage          = 1
Rate.Creature.Elite.Elite.SpellDamage     = 1
Rate.Creature.Elite.RARE.SpellDamage      = 1
Rate.Creature.Elite.RAREELITE.SpellDamage = 1
Rate.Creature.Elite.WORLDBOSS.SpellDamage = 1
Другие значения не дает выставить

### Source

Не регулируются настройки в конфиге 
Rate.Creature.Normal.SpellDamage          = 1
Rate.Creature.Elite.Elite.SpellDamage     = 1
Rate.Creature.Elite.RARE.SpellDamage      = 1
Rate.Creature.Elite.RAREELITE.SpellDamage = 1
Rate.Creature.Elite.WORLDBOSS.SpellDamage = 1
Другие значения не дает выставить

### Steps to reproduce the problem

Не регулируются настройки в конфиге 
Rate.Creature.Normal.SpellDamage          = 1
Rate.Creature.Elite.Elite.SpellDamage     = 1
Rate.Creature.Elite.RARE.SpellDamage      = 1
Rate.Creature.Elite.RAREELITE.SpellDamage = 1
Rate.Creature.Elite.WORLDBOSS.SpellDamage = 1
Другие значения не дает выставить

### AC rev. hash/commit

5495a555d683

### Operating system

Windows 10 x64, Debian 10 x64

**Comment by Winfidonarleyan** [comment]
Всё работает
